- name: test play
  hosts: awsami,ubuntu
  become: true
  tasks:
    - name: Installing httpd on AWSAMI  # sudo yum install httpd -y
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon" or
            ansible_distribution_version == "Amazon Linux3"
    - name: Installing apache2 on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu" and
            ansible_distribution_version == "22.04"
    - name: Start httpd on AWS AMI
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "Amazon"
    - name: start Apache2 on Ubuntu
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"
      
